if __name__ == "__main__":
    print(2 == 2)
    print(2 != 2)
    print(2 > 1)
    print(2 < 1)
    print(1 >= 2)
    print(1 <= 2)
    print(1 == 1.0)
    print("hello" == "hello")
    print(1 == "1")
